package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new com.tuanpm.esp_provisioning.EspProvisioningPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin esp_provisioning, com.tuanpm.esp_provisioning.EspProvisioningPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.polidea.flutter_ble_lib.FlutterBleLibPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin flutter_ble_lib_ios_15, com.polidea.flutter_ble_lib.FlutterBleLibPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.lyokone.location.LocationPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin location, com.lyokone.location.LocationPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.baseflow.permissionhandler.PermissionHandlerPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin permission_handler, com.baseflow.permissionhandler.PermissionHandlerPlugin", e);
    }
  }
}
